apiVersion: v1
kind: ConfigMap
metadata:
  name: scdf-server
  labels:
    app: scdf-server
data:
  application.yaml: |-
    management:
      metrics:
        export:
          prometheus:
            enabled: true
            rsocket:
              enabled: true
              host: prometheus-proxy
              port: 7001
    spring:
      cloud:
        dataflow:
          metrics.dashboard:
            url: 'http://k8s-default-ingressg-11f28752b8-693413371.us-east-1.elb.amazonaws.com'
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    limits:
                      memory: 1024Mi
      datasource:
        url: jdbc:postgresql://scdfdb.ccjyxy24iiyc.us-east-1.rds.amazonaws.com:5432/scdfpersistentdb
        username: adminscdf
        password: ${psql-root-password}
        driverClassName: org.postgresql.Driver
        testOnBorrow: true
        validationQuery: SELECT 1
