apiVersion: v1
kind: ConfigMap
metadata:
  name: skipper
  labels:
    app: skipper
data:
  application.yaml: |-
    spring:
      cloud:
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:
                    environmentVariables: 'SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=b-2.mskclusterscdf.1czx59.c12.kafka.us-east-1.amazonaws.com:9092 b-1.mskclusterscdf.1czx59.c12.kafka.us-east-1.amazonaws.com:9092,SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=z-1.mskclusterscdf.1czx59.c12.kafka.us-east-1.amazonaws.com:2181 z-3.mskclusterscdf.1czx59.c12.kafka.us-east-1.amazonaws.com:2181 '
                    limits:
                      memory: 1024Mi
                      cpu: 500m
                    readinessProbeDelay: 120
      datasource:
        url: jdbc:postgresql://scdfdb.ccjyxy24iiyc.us-east-1.rds.amazonaws.com:5432/skipper
        username: adminscdf
        password: ${psql-root-password}
        driverClassName: org.postgresql.Driver
        testOnBorrow: true
        validationQuery: SELECT 1
